### ISSUE TITLE
Version 0.60 will not work with bevy 0.10 

### ISSUE THREAD

**Issue by ethereumdegen** [JonahPlusPlus/bevy_atmosphere#57]
error[E0412]: cannot find type `AppTypeRegistry` in module `bevy::ecs::reflect`
 --> /home/ /.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_atmosphere-0.6.0/src/collection/nishita.rs:7:10
  |
7 | #[derive(Atmospheric, ShaderType, Reflect, Debug, Clone)]
  |          ^^^^^^^^^^^ not found in `bevy::ecs::reflect`
  |
  = note: this error originates in the derive macro `Atmospheric` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
  |
1 + use bevy::app::AppTypeRegistry;
  |
1 + use crate::collection::nishita::AppTypeRegistry;
  |
help: if you import `AppTypeRegistry`, refer to it directly
  |
7 | #[derive(Atmospheric, ShaderType, Reflect, Debug, Clone)]
  |
